### ISSUE TITLE
Can I drop you a email?

### ISSUE THREAD

**Issue by KendallDoesCoding** [Adit0507/Adit0507#1]

**Comment by Adit0507** [comment]
You can tell me here 🙂

**Comment by KendallDoesCoding** [comment]
> You can tell me here 🙂

I wanted to know if your good at JS.

**Comment by Adit0507** [comment]
I'm still at a learning stage but I have quite a good idea about JS. How can I help you ?

**Comment by KendallDoesCoding** [comment]
> I'm still at a learning stage but I have quite a good idea about JS. How can I help you ?

Are you down to help me firstly, or are you busy with other projects?

**Comment by Adit0507** [comment]
Right now I'm a bit busy with GSSoC''22 but if you share the details on what you want me to help you with, I'll surely try my best to help you

**Comment by KendallDoesCoding** [comment]
> Right now I'm a bit busy with GSSoC''22 but if you share the details on what you want me to help you with, I'll surely try my best to help you

Ok, thanks a lot!

I basically need help with JS for my project: Please have a look at: https://github.com/KendallDoesCoding/mogul-christmas/issues.... Thanks a ton!
